// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lixozidazplpracbwnjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpeG96aWRhenBscHJhY2J3bmpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0OTUxNDYsImV4cCI6MjA2MTA3MTE0Nn0.z3Gr5Vy_376y_A0PfesWpOfSZkpw60bjQBgOyvUyUHU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);